### PR TITLE
Updated Greek Language

### PR DESCRIPTION
**Pull request by ConfusedArt**
updated words and the main title to a more accurate translation, and fixed some translation errors.

### CODE REVIEW

**Comment by ConfusedArt** [comment]
This is the final update. I think it is as accurate as it can get,

**Comment by ConfusedArt** [comment]
I haven't added the new strings yet, I will do it tomorrow. Don't add it yet please.

**Comment by Al-Azif** [comment]
You made it literally as I was clicking the button to merge haha

**Comment by ConfusedArt** [comment]
That was close lol.

**Comment by ConfusedArt** [comment]
Thank you for your hard work!

**Comment by ConfusedArt** [comment]
Everything should be good to go now!

**Pull request merged**
